name: user_input
description: User input example
version: 0.0.1

environment:
  sdk: '>=2.0.0-dev.56.0 <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+13

dev_dependencies:
  build_runner: ^0.8.9
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
